### ISSUE TITLE
Unable to disable default cache policies

### ISSUE THREAD

**Issue by dougbarth** [islishude/spa-deploy-action#87]
Hello,

I'm looking into using this action to upload an SPA that has some static assets that should not have the default cache policies applied. From reading the code, I don't think it's possible to configure this action to not cache some js/css/image assets because the built in policies are added first to the Map, so they take precedence.

What I'd like to do is the following:

* js/css/images in an `assets` directory have the default policies
* js/css/images in subdirectories of the `assets` directory are not cached

Can you confirm my understanding is correct? Would it be reasonable to change the merge operation so it starts with the supplied configuraiton, and only adds the builtin config if the key is not already set?

**Comment by islishude** [comment]
Thanks for the report, I will check it out later.

**Comment by islishude** [comment]
Hi @dougbarth 

I have made a feature patch on main branch.

Can you use the main branch to test if work for your case?

fyi

```
      - name: Deploy
        uses: islishude/spa-deploy-action@main
        with:
          dir-path: 'dist'
          s3-bucket: your-s3-bucket-name
          cache-control-merge-policy: 'replace'
          cache-control: 'your custom cache-control json string'
```

the documentation

https://github.com/islishude/spa-deploy-action?tab=readme-ov-file#built-in-cache-control-mapping
